"""
portfolio_ingest.py — Yahoo Finance portfolio export -> _portfolio_holdings.yaml.

Bruno maintains his positions by hand in Yahoo Finance (My Portfolio -> "BD"). Yahoo
has had **no API since 2017** and its holdings table is virtualised, so there is no
unattended way to read the account: the CSV export is the supported path, and it is
richer than Yahoo's own help page suggests — it carries `Trade Date`, `Purchase
Price`, `Quantity`, `Commission` and `Comment` **per lot**.

This script turns that export into `_portfolio_holdings.yaml`, the source of truth for
held-detection (`exit_plan`, `thesis_dashboard`, `buy_list`). Until now that file said
"Edit via the skill, not by hand" while in fact being regenerated by hand — a
deterministic script is cheaper, repeatable and cannot mis-transcribe a number.

DRY-RUN BY DEFAULT. The target is a source-of-truth file, so it prints the diff and
writes nothing unless `--write` is passed.

Two traps this export contains, both handled here:
  * `Transaction Type` is CORRUPT. Comments containing a comma (decimal commas, e.g.
    "Taxa de Câmbio:1,82 AutoFX") are written unquoted, so the tail spills into the
    next column. 5 of 20 lots read "82 AutoFX" / "0895" / "8 USDC" instead of "BUY".
    Filtering on it would silently drop real positions, so it is never used as a
    filter — it is stitched back onto the comment instead.
  * `markets.currency_of` returns USD for a crypto pair like `BTC-EUR`. The quote
    currency of a crypto pair is its own suffix, so that is read from the symbol.

Usage:
  python portfolio_ingest.py                     # dry run: show the diff
  python portfolio_ingest.py --write             # apply it
  python portfolio_ingest.py --max-age-days 10   # louder staleness threshold
  python portfolio_ingest.py --json              # machine-readable summary
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

OUT_DIR = Path(r"C:\BD_Obsidian\Personal\Finance\StocksDaily")
HOLDINGS_FILENAME = "_portfolio_holdings.yaml"

# Where Yahoo drops the export. It names the file `quotes.csv`; Bruno's existing one is
# `portfolio.csv` (the name portfolio_sync.py already defaults to). Newest wins.
DOWNLOADS = Path(r"C:\Users\bsdias\Downloads")
EXPORT_GLOBS = ("portfolio*.csv", "quotes*.csv")

# A Yahoo portfolio export must have these columns, or it is some other CSV.
REQUIRED_COLUMNS = {"Symbol", "Quantity", "Purchase Price"}

# Beyond this the holdings file is quietly wrong, which is worse than missing.
DEFAULT_MAX_AGE_DAYS = 10

_CRYPTO_QUOTE_RE = re.compile(r"-(USD|EUR|GBP|USDT|USDC|BTC)$", re.IGNORECASE)


def log(msg: str) -> None:
    print(msg, file=sys.stderr)


# --------------------------------------------------------------------------
# Locating the export
# --------------------------------------------------------------------------
def find_export(explicit: Path | None = None, downloads: Path = DOWNLOADS) -> Path | None:
    """Newest Yahoo export. An explicit path is returned as-is (existence checked by
    the caller) so a bad --source is a loud error, not a silent fallback."""
    if explicit is not None:
        return explicit
    candidates: list[Path] = []
    for pattern in EXPORT_GLOBS:
        candidates.extend(downloads.glob(pattern))
    valid = [p for p in candidates if p.is_file()]
    if not valid:
        return None
    return max(valid, key=lambda p: p.stat().st_mtime)


def export_age_days(path: Path, today: dt.date | None = None) -> int:
    today = today or dt.date.today()
    mtime = dt.date.fromtimestamp(path.stat().st_mtime)
    return (today - mtime).days


# --------------------------------------------------------------------------
# Parsing
# --------------------------------------------------------------------------
def _safe_float(v) -> float | None:
    if v is None:
        return None
    s = str(v).strip().replace(",", "")
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def parse_trade_date(raw) -> str | None:
    """Yahoo writes YYYYMMDD. ISO and US formats are accepted too, since the column has
    changed shape before. Unparseable -> None (recorded as a lot without a date rather
    than a guessed one)."""
    s = (str(raw) or "").strip()
    if not s:
        return None
    for fmt in ("%Y%m%d", "%Y-%m-%d", "%m/%d/%Y", "%d/%m/%Y"):
        try:
            return dt.datetime.strptime(s, fmt).date().isoformat()
        except ValueError:
            continue
    return None


def lot_note(row: dict) -> str | None:
    """The lot comment, with the `Transaction Type` spill stitched back on.

    Yahoo does not quote a Comment containing a comma, so "Taxa de Câmbio:1,82 AutoFX"
    arrives as Comment="Taxa de Câmbio:1" + Transaction Type="82 AutoFX". Anything in
    Transaction Type that is not a real transaction type is therefore comment tail.
    """
    note = (row.get("Comment") or "").strip()
    tx = (row.get("Transaction Type") or "").strip()
    if tx and tx.upper() not in ("BUY", "SELL"):
        note = f"{note},{tx}" if note else tx
    return note or None


def quote_currency(symbol: str, fallback_lookup=None) -> str:
    """Quote currency of a symbol. Crypto pairs carry it in their own suffix
    (`BTC-EUR` is quoted in EUR — markets.currency_of answers USD for those)."""
    m = _CRYPTO_QUOTE_RE.search(symbol or "")
    if m:
        return m.group(1).upper()
    if fallback_lookup is not None:
        try:
            return (fallback_lookup(symbol) or "EUR").upper()
        except Exception:
            return "EUR"
    return "EUR"


def read_lots(csv_path: Path) -> tuple[list[dict], list[str]]:
    """(lot rows, warnings). A row is a lot when it carries a quantity; the rest are
    watchlist-only quote rows and are not holdings."""
    warnings: list[str] = []
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        columns = set(reader.fieldnames or [])
        missing = REQUIRED_COLUMNS - columns
        if missing:
            raise ValueError(
                f"{csv_path.name} is not a Yahoo portfolio export — missing column(s): "
                f"{', '.join(sorted(missing))}"
            )
        rows = list(reader)

    lots = []
    for row in rows:
        symbol = (row.get("Symbol") or "").strip()
        qty = _safe_float(row.get("Quantity"))
        if not symbol or not qty:
            continue
        price = _safe_float(row.get("Purchase Price"))
        if price is None:
            warnings.append(f"{symbol}: lot with quantity {qty:g} but no purchase price — skipped")
            continue
        if qty < 0:
            warnings.append(f"{symbol}: negative quantity {qty:g} — treated as a lot, verify by hand")
        lots.append({
            "symbol": symbol,
            "qty": qty,
            "price": price,
            "date": parse_trade_date(row.get("Trade Date")),
            "note": lot_note(row),
            "commission": _safe_float(row.get("Commission")),
        })
    return lots, warnings


def group_holdings(lots: list[dict], names: dict | None = None,
                   classify=None, currency_lookup=None) -> list[dict]:
    """Lots -> one holding per ticker, newest lot first, quantity-weighted avg cost.

    `names` carries the curated display names from the existing yaml: the export has no
    company-name column, so an existing name is preserved and a missing one falls back
    to the ticker. Never invented.
    """
    names = names or {}
    by_ticker: dict[str, list[dict]] = {}
    for lot in lots:
        by_ticker.setdefault(lot["symbol"], []).append(lot)

    holdings = []
    for ticker in sorted(by_ticker):
        group = sorted(by_ticker[ticker], key=lambda x: x["date"] or "", reverse=True)
        total_qty = sum(x["qty"] for x in group)
        cost = sum(x["price"] * x["qty"] for x in group)
        avg_cost = round(cost / total_qty, 4) if total_qty else None
        asset_type = "equity"
        if classify is not None:
            try:
                asset_type = classify(ticker) or "equity"
            except Exception:
                pass
        entry = {
            "ticker": ticker,
            "name": names.get(ticker) or ticker,
            "asset_type": asset_type,
            "currency": quote_currency(ticker, currency_lookup),
            "quantity": round(total_qty, 8),
            "avg_cost": avg_cost,
            "lots": [],
        }
        for x in group:
            lot: dict = {"qty": x["qty"], "price": x["price"]}
            if x["date"]:
                lot["date"] = x["date"]
            if x["note"]:
                lot["note"] = x["note"]
            entry["lots"].append(lot)
        holdings.append(entry)
    return holdings


# --------------------------------------------------------------------------
# Existing file + diff
# --------------------------------------------------------------------------
def load_existing(out_dir: Path) -> dict:
    path = out_dir / HOLDINGS_FILENAME
    try:
        import yaml
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        return {}
    except Exception as e:
        log(f"WARN: existing {HOLDINGS_FILENAME} unreadable ({type(e).__name__}: {e})")
        return {}


def curated_names(existing: dict) -> dict:
    out = {}
    for h in (existing.get("holdings") or []):
        if isinstance(h, dict) and h.get("ticker") and h.get("name"):
            out[h["ticker"]] = h["name"]
    return out


def diff_holdings(old: list, new: list) -> dict:
    """{added, removed, changed:[{ticker, field, from, to}]} — the whole point of the
    dry run, so a bad export is visible before it overwrites the source of truth."""
    old_map = {h.get("ticker"): h for h in (old or []) if isinstance(h, dict)}
    new_map = {h["ticker"]: h for h in new}
    added = sorted(set(new_map) - set(old_map))
    removed = sorted(set(old_map) - set(new_map))
    changed = []
    for ticker in sorted(set(old_map) & set(new_map)):
        for field in ("quantity", "avg_cost", "currency", "asset_type"):
            before, after = old_map[ticker].get(field), new_map[ticker].get(field)
            if isinstance(before, float) and isinstance(after, float):
                if abs(before - after) < 1e-9:
                    continue
            elif before == after:
                continue
            changed.append({"ticker": ticker, "field": field, "from": before, "to": after})
    return {"added": added, "removed": removed, "changed": changed}


def build_document(holdings: list[dict], source: Path, today_iso: str) -> dict:
    return {
        "version": 1,
        "last_updated": today_iso,
        "source": (
            f"Generated by portfolio_ingest.py from {source} (Yahoo Finance export). "
            f"Only rows with purchase lots were imported; quote-only rows are watchlist, "
            f"not holdings."
        ),
        "holdings": holdings,
    }


HEADER_COMMENT = (
    "# Source of truth for /bd-stocks-portfolio and held-detection (exit_plan, thesis\n"
    "# stance, buy_list). Regenerate with scripts/portfolio_ingest.py --write after\n"
    "# exporting the Yahoo portfolio; do not edit by hand.\n"
)


def write_holdings(out_dir: Path, document: dict) -> Path:
    import yaml
    path = out_dir / HOLDINGS_FILENAME
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True, default_flow_style=False)
    path.write_text(HEADER_COMMENT + body, encoding="utf-8")
    return path


# --------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=None, help="Yahoo export CSV (default: newest in Downloads)")
    ap.add_argument("--out-dir", default=str(OUT_DIR))
    ap.add_argument("--write", action="store_true", help="apply the change (default: dry run)")
    ap.add_argument("--max-age-days", type=int, default=DEFAULT_MAX_AGE_DAYS)
    ap.add_argument("--json", action="store_true", help="machine-readable summary on stdout")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    source = find_export(Path(args.source) if args.source else None)
    if source is None:
        log(f"ERROR: no Yahoo export found in {DOWNLOADS} (looked for {', '.join(EXPORT_GLOBS)})")
        log("Export it: Yahoo Finance -> My Portfolio -> BD -> Download -> Save as CSV")
        return 1
    if not source.exists():
        log(f"ERROR: export not found: {source}")
        return 1

    age = export_age_days(source)
    stale = age > args.max_age_days
    log(f"Export: {source} ({age}d old)")
    if stale:
        log(f"WARN: export is {age} days old (> {args.max_age_days}) — re-export before "
            f"trusting held-detection or cost basis")

    try:
        lots, warnings = read_lots(source)
    except ValueError as e:
        log(f"ERROR: {e}")
        return 1
    for w in warnings:
        log(f"WARN: {w}")

    classify = currency_lookup = None
    try:
        import markets
        currency_lookup = markets.currency_of
        from portfolio_sync import classify_nonequity
        classify = classify_nonequity
    except Exception as e:
        log(f"WARN: ticker classifiers unavailable ({type(e).__name__}: {e}) — "
            f"asset_type defaults to equity")

    existing = load_existing(out_dir)
    holdings = group_holdings(lots, curated_names(existing), classify, currency_lookup)
    delta = diff_holdings(existing.get("holdings") or [], holdings)

    log(f"Parsed {len(lots)} lots -> {len(holdings)} holdings")
    log(f"  added:   {', '.join(delta['added']) or '(none)'}")
    log(f"  removed: {', '.join(delta['removed']) or '(none)'}")
    if delta["changed"]:
        for c in delta["changed"]:
            log(f"  changed: {c['ticker']}.{c['field']}: {c['from']} -> {c['to']}")
    else:
        log("  changed: (none)")

    wrote = None
    if args.write:
        document = build_document(holdings, source, dt.date.today().isoformat())
        wrote = str(write_holdings(out_dir, document))
        log(f"WROTE {wrote}")
    else:
        log("DRY RUN — nothing written. Re-run with --write to apply.")

    summary = {
        "source": str(source), "age_days": age, "stale": stale,
        "lots": len(lots), "holdings": len(holdings),
        "added": delta["added"], "removed": delta["removed"],
        "changed": delta["changed"], "warnings": warnings, "written": wrote,
    }
    if args.json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
